# (C) Crown Copyright 2024-2025, Met Office.
# The LICENSE.md file contains full licensing details.
# Configure black.
[tool.black]
line-length = 79
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | build
    | dist
  )/
)
'''



# Configure pytest.
[tool.pytest.ini_options]
testpaths = ["CMEW"]
filterwarnings = [
    # Ignore deprecation warnings from webob, esmpy and pkg_resources:
    "ignore:'cgi' is deprecated and slated for removal in Python 3.13:DeprecationWarning",
    "ignore:Implicit None on return values is deprecated:DeprecationWarning",
    "ignore:Deprecated call to `pkg_resources.declare_namespace:DeprecationWarning",
    # Ignore user warnings from pybtex:
    "ignore:pkg_resources is deprecated as an API:UserWarning",
]
