# (C) Crown Copyright 2024-2026, Met Office.
# The LICENSE.md file contains full licensing details.
name: cmew

channels:
  - conda-forge

dependencies:
  - cylc-flow
  - cylc-rose
  - esmvalcore
  - metomi-rose
  - pre-commit
  - pytest
  - sphinx
  - sphinx_rtd_theme
